# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 690)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 0, 1011, 721))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Desktop/other/bg.png"))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(950, -40, 71, 771))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Desktop/other/right_border4.png"))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 211, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../Desktop/other/smth2.png"))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 0, 731, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Desktop/other/top_border2png.png"))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 221, 691))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../../Desktop/other/left_border.png"))
        self.label_6.setObjectName("label_6")
        self.settings_btn = QtWidgets.QPushButton(Form)
        self.settings_btn.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.settings_btn.setObjectName("settings_btn")
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setGeometry(QtCore.QRect(80, 20, 61, 61))
        self.search_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_btn.setObjectName("search_btn")
        self.add_group_btn = QtWidgets.QPushButton(Form)
        self.add_group_btn.setGeometry(QtCore.QRect(150, 20, 61, 61))
        self.add_group_btn.setObjectName("add_group_btn")
        self.group_list = QtWidgets.QListWidget(Form)
        self.group_list.setGeometry(QtCore.QRect(10, 100, 201, 581))
        self.group_list.setObjectName("group_list")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 100, 131, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Desktop/other/smth_else1.png"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.settings_btn.setText(_translate("Form", "sttngs"))
        self.search_btn.setText(_translate("Form", "search"))
        self.add_group_btn.setText(_translate("Form", "add gr"))
